# Generated by Django 6.0.1 on 2026-01-21 04:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VolleyballMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_sets_won', models.IntegerField(default=0)),
                ('away_sets_won', models.IntegerField(default=0)),
                ('match_time', models.DateTimeField()),
                ('status', models.CharField(choices=[('UPCOMING', 'Upcoming'), ('LIVE', 'Live'), ('FINISHED', 'Finished')], default='UPCOMING', max_length=10)),
                ('highlights_url', models.URLField(blank=True)),
                ('away_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='volleyball_away', to='core.team')),
                ('home_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='volleyball_home', to='core.team')),
            ],
        ),
    ]
