# Generated by Django 6.0.1 on 2026-01-21 07:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='city',
        ),
        migrations.AddField(
            model_name='player',
            name='position',
            field=models.CharField(default='TBD', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='player',
            name='jersey_number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='team',
            name='logo',
            field=models.ImageField(default=0, upload_to='logos/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='team',
            name='sport',
            field=models.CharField(choices=[('FOOTBALL', 'Football'), ('CRICKET', 'Cricket'), ('VOLLEYBALL', 'Volleyball')], max_length=20),
        ),
        migrations.CreateModel(
            name='CricketMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('UPCOMING', 'Upcoming'), ('LIVE', 'Live'), ('FINISHED', 'Finished')], default='UPCOMING', max_length=10)),
                ('highlights_url', models.URLField(blank=True, null=True)),
                ('home_runs', models.IntegerField(default=0)),
                ('home_wickets', models.IntegerField(default=0)),
                ('away_runs', models.IntegerField(default=0)),
                ('away_wickets', models.IntegerField(default=0)),
                ('away_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cr_away', to='core.team')),
                ('home_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cr_home', to='core.team')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FootballMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('UPCOMING', 'Upcoming'), ('LIVE', 'Live'), ('FINISHED', 'Finished')], default='UPCOMING', max_length=10)),
                ('highlights_url', models.URLField(blank=True, null=True)),
                ('home_score', models.IntegerField(default=0)),
                ('away_score', models.IntegerField(default=0)),
                ('away_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fb_away', to='core.team')),
                ('home_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fb_home', to='core.team')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VolleyballMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('UPCOMING', 'Upcoming'), ('LIVE', 'Live'), ('FINISHED', 'Finished')], default='UPCOMING', max_length=10)),
                ('highlights_url', models.URLField(blank=True, null=True)),
                ('home_sets_won', models.IntegerField(default=0)),
                ('away_sets_won', models.IntegerField(default=0)),
                ('away_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vol_away', to='core.team')),
                ('home_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vol_home', to='core.team')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
