# Generated by Django 6.0.1 on 2026-01-21 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_team_city_player_position_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cricketmatch',
            name='match_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='footballmatch',
            name='match_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='volleyballmatch',
            name='match_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
