# Generated by Django 5.2.10 on 2026-02-19 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_teacherprofile_studentprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='cricketmatch',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name='footballmatch',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name='team',
            name='side_logo',
            field=models.ImageField(blank=True, null=True, upload_to='sides/'),
        ),
        migrations.AddField(
            model_name='volleyballmatch',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='sport',
            field=models.CharField(choices=[('FOOTBALL', 'Football'), ('CRICKET', 'Cricket'), ('VOLLEYBALL', 'Volleyball'), ('BADMINTON', 'Badminton')], max_length=20),
        ),
    ]
