# Generated by Django 5.2.10 on 2026-02-19 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_cricketmatch_slug_footballmatch_slug_team_side_logo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cricketmatch',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='footballmatch',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='team',
            name='side_logo',
        ),
        migrations.RemoveField(
            model_name='volleyballmatch',
            name='slug',
        ),
        migrations.AlterField(
            model_name='team',
            name='sport',
            field=models.CharField(choices=[('FOOTBALL', 'Football'), ('CRICKET', 'Cricket'), ('VOLLEYBALL', 'Volleyball')], max_length=20),
        ),
    ]
