# Generated by Django 5.2.10 on 2026-02-19 09:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_cricketmatch_slug_remove_footballmatch_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='sport',
            field=models.CharField(choices=[('FOOTBALL', 'Football'), ('CRICKET', 'Cricket'), ('VOLLEYBALL', 'Volleyball'), ('TENNIS', 'Tennis'), ('BASKETBALL', 'Basketball'), ('BADMINTON', 'Badminton'), ('BOXING', 'Boxing'), ('MOTORSPORT', 'Motorsport'), ('GOLF', 'Golf'), ('HANDBALL', 'Handball'), ('ICE_HOCKEY', 'Ice Hockey'), ('RUGBY', 'Rugby'), ('SNOOKER', 'Snooker'), ('TABLE_TENNIS', 'Table Tennis'), ('WATER_POLO', 'Water Polo'), ('DARTS', 'Darts'), ('ESPORTS', 'Esports'), ('HORSE_RACING', 'Horse Racing'), ('BASEBALL', 'Baseball'), ('KABADDI', 'Kabaddi'), ('ATHLETICS', 'Athletics')], max_length=50),
        ),
        migrations.CreateModel(
            name='UniversalMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('UPCOMING', 'Upcoming'), ('LIVE', 'Live'), ('FINISHED', 'Finished')], default='UPCOMING', max_length=10)),
                ('highlights_url', models.URLField(blank=True, null=True)),
                ('match_datetime', models.DateTimeField(blank=True, null=True)),
                ('sport', models.CharField(choices=[('FOOTBALL', 'Football'), ('CRICKET', 'Cricket'), ('VOLLEYBALL', 'Volleyball'), ('TENNIS', 'Tennis'), ('BASKETBALL', 'Basketball'), ('BADMINTON', 'Badminton'), ('BOXING', 'Boxing'), ('MOTORSPORT', 'Motorsport'), ('GOLF', 'Golf'), ('HANDBALL', 'Handball'), ('ICE_HOCKEY', 'Ice Hockey'), ('RUGBY', 'Rugby'), ('SNOOKER', 'Snooker'), ('TABLE_TENNIS', 'Table Tennis'), ('WATER_POLO', 'Water Polo'), ('DARTS', 'Darts'), ('ESPORTS', 'Esports'), ('HORSE_RACING', 'Horse Racing'), ('BASEBALL', 'Baseball'), ('KABADDI', 'Kabaddi'), ('ATHLETICS', 'Athletics')], max_length=50)),
                ('home_score', models.CharField(default='0', max_length=20)),
                ('away_score', models.CharField(default='0', max_length=20)),
                ('match_info', models.CharField(blank=True, help_text='e.g., Round 1, Q3, or Set 2', max_length=100, null=True)),
                ('away_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uni_away', to='core.team')),
                ('home_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uni_home', to='core.team')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
