# Generated by Django 5.2.10 on 2026-02-19 09:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_team_sport_universalmatch'),
    ]

    operations = [
        migrations.AddField(
            model_name='cricketmatch',
            name='away_overs',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=4),
        ),
        migrations.AddField(
            model_name='cricketmatch',
            name='current_status_text',
            field=models.CharField(blank=True, help_text='e.g. India needs 20 runs to win', max_length=255),
        ),
        migrations.AddField(
            model_name='cricketmatch',
            name='home_overs',
            field=models.DecimalField(decimal_places=1, default=0.0, help_text='e.g. 15.2', max_digits=4),
        ),
        migrations.AddField(
            model_name='cricketmatch',
            name='is_live_now',
            field=models.BooleanField(default=False, help_text='Toggle this for the blinking LIVE badge'),
        ),
        migrations.AddField(
            model_name='cricketmatch',
            name='toss_decision',
            field=models.CharField(blank=True, choices=[('BAT', 'Batting'), ('BOWL', 'Bowling')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='cricketmatch',
            name='toss_winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cr_toss_wins', to='core.team'),
        ),
    ]
