# Generated by Django 5.2.10 on 2026-02-19 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_cricketmatch_away_overs_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='total_points',
            field=models.IntegerField(default=0, help_text='Total points calculated from match results'),
        ),
        migrations.AlterField(
            model_name='cricketmatch',
            name='current_status_text',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='cricketmatch',
            name='home_overs',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='cricketmatch',
            name='is_live_now',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='universalmatch',
            name='match_info',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
