# Generated by Django 5.2.10 on 2026-02-19 11:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_team_total_points_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='total_points',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='CricketBattingPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(max_length=100)),
                ('runs', models.IntegerField(default=0)),
                ('balls', models.IntegerField(default=0)),
                ('fours', models.IntegerField(default=0)),
                ('sixes', models.IntegerField(default=0)),
                ('dismissal_info', models.CharField(blank=True, help_text='e.g., c Pandya b Ngidi', max_length=255)),
                ('is_not_out', models.BooleanField(default=False)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batting_performances', to='core.cricketmatch')),
            ],
        ),
    ]
