# Generated by Django 5.2.10 on 2026-02-19 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_team_total_points_cricketbattingperformance'),
    ]

    operations = [
        migrations.AddField(
            model_name='cricketmatch',
            name='data_source',
            field=models.CharField(choices=[('MANUAL', 'Manual (Internal)'), ('API', 'External API (Auto)')], default='MANUAL', max_length=10),
        ),
        migrations.AddField(
            model_name='cricketmatch',
            name='external_api_id',
            field=models.CharField(blank=True, help_text='ID from sports API provider', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='footballmatch',
            name='data_source',
            field=models.CharField(choices=[('MANUAL', 'Manual (Internal)'), ('API', 'External API (Auto)')], default='MANUAL', max_length=10),
        ),
        migrations.AddField(
            model_name='footballmatch',
            name='external_api_id',
            field=models.CharField(blank=True, help_text='ID from sports API provider', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='universalmatch',
            name='data_source',
            field=models.CharField(choices=[('MANUAL', 'Manual (Internal)'), ('API', 'External API (Auto)')], default='MANUAL', max_length=10),
        ),
        migrations.AddField(
            model_name='universalmatch',
            name='external_api_id',
            field=models.CharField(blank=True, help_text='ID from sports API provider', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='volleyballmatch',
            name='data_source',
            field=models.CharField(choices=[('MANUAL', 'Manual (Internal)'), ('API', 'External API (Auto)')], default='MANUAL', max_length=10),
        ),
        migrations.AddField(
            model_name='volleyballmatch',
            name='external_api_id',
            field=models.CharField(blank=True, help_text='ID from sports API provider', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='total_points',
            field=models.IntegerField(default=0, help_text='Total points calculated from match results'),
        ),
        migrations.DeleteModel(
            name='CricketBattingPerformance',
        ),
    ]
