# Generated by Django 6.0.1 on 2026-03-06 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_cricketmatch_data_source_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cricketmatch',
            name='attendance',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cricketmatch',
            name='city',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AddField(
            model_name='cricketmatch',
            name='competition_name',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='cricketmatch',
            name='country',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AddField(
            model_name='cricketmatch',
            name='referee',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='cricketmatch',
            name='round_name',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='cricketmatch',
            name='season_name',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='cricketmatch',
            name='venue',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='footballmatch',
            name='attendance',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='footballmatch',
            name='city',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AddField(
            model_name='footballmatch',
            name='competition_name',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='footballmatch',
            name='country',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AddField(
            model_name='footballmatch',
            name='referee',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='footballmatch',
            name='round_name',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='footballmatch',
            name='season_name',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='footballmatch',
            name='venue',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='universalmatch',
            name='attendance',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='universalmatch',
            name='city',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AddField(
            model_name='universalmatch',
            name='competition_name',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='universalmatch',
            name='country',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AddField(
            model_name='universalmatch',
            name='referee',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='universalmatch',
            name='round_name',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='universalmatch',
            name='season_name',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='universalmatch',
            name='venue',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='volleyballmatch',
            name='attendance',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='volleyballmatch',
            name='city',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AddField(
            model_name='volleyballmatch',
            name='competition_name',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='volleyballmatch',
            name='country',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AddField(
            model_name='volleyballmatch',
            name='referee',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='volleyballmatch',
            name='round_name',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='volleyballmatch',
            name='season_name',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='volleyballmatch',
            name='venue',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
    ]
