# Generated by Django 5.2.10 on 2026-03-06 08:38

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_team_logo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='player',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='team',
            options={'ordering': ['-total_points', 'name']},
        ),
        migrations.RemoveField(
            model_name='cricketmatch',
            name='competition_name',
        ),
        migrations.RemoveField(
            model_name='cricketmatch',
            name='season_name',
        ),
        migrations.RemoveField(
            model_name='footballmatch',
            name='competition_name',
        ),
        migrations.RemoveField(
            model_name='footballmatch',
            name='season_name',
        ),
        migrations.RemoveField(
            model_name='universalmatch',
            name='competition_name',
        ),
        migrations.RemoveField(
            model_name='universalmatch',
            name='season_name',
        ),
        migrations.RemoveField(
            model_name='volleyballmatch',
            name='competition_name',
        ),
        migrations.RemoveField(
            model_name='volleyballmatch',
            name='season_name',
        ),
        migrations.AddField(
            model_name='cricketmatch',
            name='away_innings1_overs',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='cricketmatch',
            name='away_innings1_runs',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cricketmatch',
            name='away_innings1_wickets',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cricketmatch',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='cricketmatch',
            name='home_innings1_overs',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='cricketmatch',
            name='home_innings1_runs',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cricketmatch',
            name='home_innings1_wickets',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cricketmatch',
            name='match_format',
            field=models.CharField(choices=[('T20', 'T20'), ('ODI', 'ODI'), ('TEST', 'Test'), ('T10', 'T10'), ('T100', 'The Hundred')], default='T20', max_length=20),
        ),
        migrations.AddField(
            model_name='cricketmatch',
            name='temperature',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cricketmatch',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='cricketmatch',
            name='weather',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='footballmatch',
            name='away_corners',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='footballmatch',
            name='away_fouls',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='footballmatch',
            name='away_halftime_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='footballmatch',
            name='away_pens',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='footballmatch',
            name='away_possession',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='footballmatch',
            name='away_red_cards',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='footballmatch',
            name='away_shots',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='footballmatch',
            name='away_shots_on_target',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='footballmatch',
            name='away_win_odds',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='footballmatch',
            name='away_yellow_cards',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='footballmatch',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='footballmatch',
            name='draw_odds',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='footballmatch',
            name='home_corners',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='footballmatch',
            name='home_fouls',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='footballmatch',
            name='home_halftime_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='footballmatch',
            name='home_pens',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='footballmatch',
            name='home_possession',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='footballmatch',
            name='home_red_cards',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='footballmatch',
            name='home_shots',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='footballmatch',
            name='home_shots_on_target',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='footballmatch',
            name='home_win_odds',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='footballmatch',
            name='home_yellow_cards',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='footballmatch',
            name='temperature',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='footballmatch',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='footballmatch',
            name='weather',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='player',
            name='assists',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='biography',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='player',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='flashscore_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='goals_scored',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='height',
            field=models.FloatField(blank=True, help_text='Height in cm', null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='player',
            name='matches_played',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='nationality',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='player',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='players/photos/'),
        ),
        migrations.AddField(
            model_name='player',
            name='weight',
            field=models.FloatField(blank=True, help_text='Weight in kg', null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='country',
            field=models.CharField(default='International', max_length=100),
        ),
        migrations.AddField(
            model_name='team',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='team',
            name='flashscore_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='founded_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='rank',
            field=models.IntegerField(blank=True, help_text='Current ranking position', null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='short_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='team',
            name='stadium',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='team',
            name='website',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='universalmatch',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='universalmatch',
            name='sport_details',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='universalmatch',
            name='temperature',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='universalmatch',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='universalmatch',
            name='weather',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='volleyballmatch',
            name='away_set1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='volleyballmatch',
            name='away_set2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='volleyballmatch',
            name='away_set3',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='volleyballmatch',
            name='away_set4',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='volleyballmatch',
            name='away_set5',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='volleyballmatch',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='volleyballmatch',
            name='home_set1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='volleyballmatch',
            name='home_set2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='volleyballmatch',
            name='home_set3',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='volleyballmatch',
            name='home_set4',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='volleyballmatch',
            name='home_set5',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='volleyballmatch',
            name='temperature',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='volleyballmatch',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='volleyballmatch',
            name='weather',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='cricketmatch',
            name='status',
            field=models.CharField(choices=[('UPCOMING', 'Upcoming'), ('LIVE', 'Live'), ('FINISHED', 'Finished'), ('POSTPONED', 'Postponed'), ('CANCELLED', 'Cancelled')], default='UPCOMING', max_length=10),
        ),
        migrations.AlterField(
            model_name='footballmatch',
            name='status',
            field=models.CharField(choices=[('UPCOMING', 'Upcoming'), ('LIVE', 'Live'), ('FINISHED', 'Finished'), ('POSTPONED', 'Postponed'), ('CANCELLED', 'Cancelled')], default='UPCOMING', max_length=10),
        ),
        migrations.AlterField(
            model_name='player',
            name='jersey_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='position',
            field=models.CharField(blank=True, choices=[('GK', 'Goalkeeper'), ('DEF', 'Defender'), ('MID', 'Midfielder'), ('FWD', 'Forward'), ('ALL', 'All-Rounder'), ('BATS', 'Batsman'), ('BOWL', 'Bowler'), ('WK', 'Wicket Keeper'), ('SINGLE', 'Singles'), ('DOUBLE', 'Doubles'), ('MIXED', 'Mixed Doubles')], max_length=50),
        ),
        migrations.AlterField(
            model_name='player',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='players', to='core.team'),
        ),
        migrations.AlterField(
            model_name='team',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='teams/logos/'),
        ),
        migrations.AlterField(
            model_name='universalmatch',
            name='status',
            field=models.CharField(choices=[('UPCOMING', 'Upcoming'), ('LIVE', 'Live'), ('FINISHED', 'Finished'), ('POSTPONED', 'Postponed'), ('CANCELLED', 'Cancelled')], default='UPCOMING', max_length=10),
        ),
        migrations.AlterField(
            model_name='volleyballmatch',
            name='status',
            field=models.CharField(choices=[('UPCOMING', 'Upcoming'), ('LIVE', 'Live'), ('FINISHED', 'Finished'), ('POSTPONED', 'Postponed'), ('CANCELLED', 'Cancelled')], default='UPCOMING', max_length=10),
        ),
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('sport', models.CharField(choices=[('FOOTBALL', 'Football'), ('CRICKET', 'Cricket'), ('VOLLEYBALL', 'Volleyball'), ('TENNIS', 'Tennis'), ('BASKETBALL', 'Basketball'), ('BADMINTON', 'Badminton'), ('BOXING', 'Boxing'), ('MOTORSPORT', 'Motorsport'), ('GOLF', 'Golf'), ('HANDBALL', 'Handball'), ('ICE_HOCKEY', 'Ice Hockey'), ('RUGBY', 'Rugby'), ('SNOOKER', 'Snooker'), ('TABLE_TENNIS', 'Table Tennis'), ('WATER_POLO', 'Water Polo'), ('DARTS', 'Darts'), ('ESPORTS', 'Esports'), ('HORSE_RACING', 'Horse Racing'), ('BASEBALL', 'Baseball'), ('KABADDI', 'Kabaddi'), ('ATHLETICS', 'Athletics')], max_length=50)),
                ('country', models.CharField(default='International', max_length=100)),
                ('category', models.CharField(help_text='e.g., League, Cup, Tournament', max_length=100)),
                ('season', models.CharField(blank=True, max_length=50)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='competitions/logos/')),
                ('is_active', models.BooleanField(default=True)),
                ('priority', models.IntegerField(default=0, help_text='Higher priority shows first')),
                ('flashscore_id', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'ordering': ['-priority', 'sport', 'country', 'name'],
                'unique_together': {('name', 'sport', 'country')},
            },
        ),
        migrations.AddField(
            model_name='cricketmatch',
            name='competition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cr_matches', to='core.competition'),
        ),
        migrations.AddField(
            model_name='footballmatch',
            name='competition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fb_matches', to='core.competition'),
        ),
        migrations.AddField(
            model_name='universalmatch',
            name='competition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uni_matches', to='core.competition'),
        ),
        migrations.AddField(
            model_name='volleyballmatch',
            name='competition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vol_matches', to='core.competition'),
        ),
        migrations.CreateModel(
            name='MatchEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_type', models.CharField(max_length=20)),
                ('match_id', models.IntegerField()),
                ('event_type', models.CharField(choices=[('GOAL', 'Goal'), ('ASSIST', 'Assist'), ('YELLOW_CARD', 'Yellow Card'), ('RED_CARD', 'Red Card'), ('SUBSTITUTION', 'Substitution'), ('PENALTY', 'Penalty'), ('OWN_GOAL', 'Own Goal'), ('VAR', 'VAR Review'), ('INJURY', 'Injury'), ('HALF_TIME', 'Half Time'), ('FULL_TIME', 'Full Time')], max_length=20)),
                ('minute', models.IntegerField()),
                ('description', models.CharField(max_length=200)),
                ('extra_info', models.JSONField(blank=True, default=dict)),
                ('player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.player')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.team')),
            ],
            options={
                'ordering': ['minute'],
            },
        ),
        migrations.CreateModel(
            name='NewsArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('summary', models.CharField(max_length=500)),
                ('author', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='news/images/')),
                ('sport', models.CharField(blank=True, choices=[('FOOTBALL', 'Football'), ('CRICKET', 'Cricket'), ('VOLLEYBALL', 'Volleyball'), ('TENNIS', 'Tennis'), ('BASKETBALL', 'Basketball'), ('BADMINTON', 'Badminton'), ('BOXING', 'Boxing'), ('MOTORSPORT', 'Motorsport'), ('GOLF', 'Golf'), ('HANDBALL', 'Handball'), ('ICE_HOCKEY', 'Ice Hockey'), ('RUGBY', 'Rugby'), ('SNOOKER', 'Snooker'), ('TABLE_TENNIS', 'Table Tennis'), ('WATER_POLO', 'Water Polo'), ('DARTS', 'Darts'), ('ESPORTS', 'Esports'), ('HORSE_RACING', 'Horse Racing'), ('BASEBALL', 'Baseball'), ('KABADDI', 'Kabaddi'), ('ATHLETICS', 'Athletics')], max_length=50)),
                ('is_trending', models.BooleanField(default=False)),
                ('is_featured', models.BooleanField(default=False)),
                ('view_count', models.IntegerField(default=0)),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('competition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='news', to='core.competition')),
                ('players', models.ManyToManyField(blank=True, related_name='news', to='core.player')),
                ('teams', models.ManyToManyField(blank=True, related_name='news', to='core.team')),
            ],
            options={
                'ordering': ['-published_at'],
            },
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_current', models.BooleanField(default=False)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seasons', to='core.competition')),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.AddField(
            model_name='cricketmatch',
            name='season',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.season'),
        ),
        migrations.AddField(
            model_name='footballmatch',
            name='season',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.season'),
        ),
        migrations.AddField(
            model_name='universalmatch',
            name='season',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.season'),
        ),
        migrations.AddField(
            model_name='volleyballmatch',
            name='season',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.season'),
        ),
        migrations.CreateModel(
            name='UserFavorites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_notifications', models.BooleanField(default=True)),
                ('push_notifications', models.BooleanField(default=True)),
                ('favorite_match_notifications', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('favorite_competitions', models.ManyToManyField(blank=True, related_name='favorited_by', to='core.competition')),
                ('favorite_players', models.ManyToManyField(blank=True, related_name='favorited_by', to='core.player')),
                ('favorite_teams', models.ManyToManyField(blank=True, related_name='favorited_by', to='core.team')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HeadToHead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sport', models.CharField(choices=[('FOOTBALL', 'Football'), ('CRICKET', 'Cricket'), ('VOLLEYBALL', 'Volleyball'), ('TENNIS', 'Tennis'), ('BASKETBALL', 'Basketball'), ('BADMINTON', 'Badminton'), ('BOXING', 'Boxing'), ('MOTORSPORT', 'Motorsport'), ('GOLF', 'Golf'), ('HANDBALL', 'Handball'), ('ICE_HOCKEY', 'Ice Hockey'), ('RUGBY', 'Rugby'), ('SNOOKER', 'Snooker'), ('TABLE_TENNIS', 'Table Tennis'), ('WATER_POLO', 'Water Polo'), ('DARTS', 'Darts'), ('ESPORTS', 'Esports'), ('HORSE_RACING', 'Horse Racing'), ('BASEBALL', 'Baseball'), ('KABADDI', 'Kabaddi'), ('ATHLETICS', 'Athletics')], max_length=50)),
                ('total_matches', models.IntegerField(default=0)),
                ('team1_wins', models.IntegerField(default=0)),
                ('team2_wins', models.IntegerField(default=0)),
                ('draws', models.IntegerField(default=0)),
                ('team1_goals_for', models.IntegerField(default=0)),
                ('team2_goals_for', models.IntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('team1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='h2h_team1', to='core.team')),
                ('team2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='h2h_team2', to='core.team')),
            ],
            options={
                'unique_together': {('team1', 'team2', 'sport')},
            },
        ),
        migrations.CreateModel(
            name='PlayerRanking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ranking_type', models.CharField(choices=[('ATP', 'ATP Singles'), ('WTA', 'WTA Singles'), ('ATP_DOUBLES', 'ATP Doubles'), ('WTA_DOUBLES', 'WTA Doubles'), ('FIFA', 'FIFA World Ranking'), ('ICCRANKING', 'ICC Cricket Ranking'), ('BWF', 'BWF World Ranking')], max_length=20)),
                ('position', models.IntegerField()),
                ('points', models.IntegerField(default=0)),
                ('movement', models.IntegerField(default=0, help_text='Position change from previous ranking')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rankings', to='core.player')),
            ],
            options={
                'ordering': ['ranking_type', 'position'],
                'unique_together': {('player', 'ranking_type')},
            },
        ),
        migrations.CreateModel(
            name='Standing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField()),
                ('played', models.IntegerField(default=0)),
                ('won', models.IntegerField(default=0)),
                ('drawn', models.IntegerField(default=0)),
                ('lost', models.IntegerField(default=0)),
                ('goals_for', models.IntegerField(default=0)),
                ('goals_against', models.IntegerField(default=0)),
                ('goal_difference', models.IntegerField(default=0)),
                ('points', models.IntegerField(default=0)),
                ('form', models.CharField(blank=True, max_length=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='standings', to='core.competition')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='standings', to='core.season')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='standings', to='core.team')),
            ],
            options={
                'ordering': ['competition', 'season', 'position'],
                'unique_together': {('competition', 'season', 'team')},
            },
        ),
    ]
